### ISSUE TITLE
It fails with react@15

### ISSUE THREAD

**Issue by adriantoine** [bruderstein/unexpected-react#17]
Hi!

`react@15` has been released yesterday and they removed `react/addons` which has been deprecated in `react@0.14`, now you have to install the npm module `react-addons-test-utils` to get the React Test Utils.

I just tried this approach and I get this error as soon as I just require `unexpected-react`:
```
Error: Cannot find module 'fbjs/lib/warning'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/node_modules/react/addons.js:3:15)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/babel-register/lib/node.js:134:7)
    at extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/unexpected-react/src/deepAssertions.js:4:66)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/babel-register/lib/node.js:134:7)
    at extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/unexpected-react/src/unexpected-react.js:3:28)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/babel-register/lib/node.js:134:7)
    at extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/test/Button.spec.js:12:1)
    at Module._compile (module.js:413:34)
    at extensions.(anonymous function) (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/adrien/Projects/dev-setup/tray/src/github.com/trayio/frontend-apps/new-website/node_modules/ava/lib/test-worker.js:93:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by bruderstein** [comment]
The current version is specifically compatible with 0.13.x and 0.14.x, as
per the peerDependency entry. I'll release a 0.14.x and 0.15.x version this
weekend.

**Comment by adriantoine** [comment]
Great!

**Comment by bruderstein** [comment]
Just a quick update - I fell ill at the weekend,  so I've not had the strength to update this. Hopefully by the end of the week I'll be able to sort this out.  
In the meantime, if anyone wants to send a PR to move the peerDep to `0.14.x || 15.x.x` and update the code to use only the 0.14 apis, that would be awesome!

**Comment by adriantoine** [comment]
No problem at all, you're not forced to do it, take you time!

**Comment by choffmeister** [comment]
Is there anything that one can help you with? Looking forward to using React 15

**Comment by bruderstein** [comment]
@choffmeister thanks. I think it's probably reasonably straightforward, and should just be the standard 0.13 - > 0.14 upgrade, so change the `render` calls to reference ReactDOM (I think that should just be in the tests), and the other few bits and pieces. 

I think the only ugly thing is one that @mridgway pointed out on twitter, is we'll need to use react-addons-test-utils as a peer dependency, as we need to use whatever version the project is using. 

A PR with that would be great, and would mean we'd get 15 support much sooner ;)

**Comment by gustavnikolaj** [comment]
In more bad news, React.findDOMNode is also deprecated and removed, so now you need to include react-dom as a peer dep too :( I have a PR ready for review, referenced above. :-)

**Comment by bruderstein** [comment]
Fixed in v3.0.0 (thanks for #19 from @gustavnikolaj!)

**Comment by choffmeister** [comment]
Whooot? Very big thx! I will immediately try this out...."

**Comment by choffmeister** [comment]
Works very fine. Only `npm list`/`npm shrinkwrap` now fail in my project with

```
npm ERR! peer invalid: react@^0.13.0 || ^0.14.0, required by react-render-hook@0.1.2
npm ERR! peer invalid: react@^0.13.0 || ^0.14.0, required by unexpected-htmllike-jsx-adapter@0.5.1
```

I am currently looking into the two project to update them accordingly
