### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by inyono** [bruderstein/unexpected-react#40]
Does this project also work for React Native (or is it planned to do so in the future)? When adding `unexpected-react` as a plugin, I get the following error:

```.js
    TypeError: window.WebSocket is not a constructor

      at setupDevtools (node_modules/react-native/Libraries/Core/Devtools/setupDevtools.js:25:8)
      at Object.<anonymous> (node_modules/react-native/Libraries/Core/InitializeCore.js:199:1)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeDefaultInjection.js:20:1)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNative.js:17:33)
      at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native.js:188:25)
```

**Comment by bruderstein** [comment]
It's kinda of a long term goal, but not something that there's any concrete plans for yet.

This may become easier with Fiber and custom renderers, but it may not. I'll leave this open as a feature request :)

**Comment by bruderstein** [comment]
In version 5.0.0, you can `require('unexpected-react/react-native')` and you get shallow renderer support (using jest).  We've not done much with this, so let us know how this goes!

**Comment by inyono** [comment]
Nice, looking forward to try it out 👍
